// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void Anim1_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
extern lv_obj_t *ui_Main_Screen;
void ui_event_Roller2( lv_event_t * e);
extern lv_obj_t *ui_Roller2;
// SCREEN: ui_Light_Control_Screen
void ui_Light_Control_Screen_screen_init(void);
extern lv_obj_t *ui_Light_Control_Screen;
extern lv_obj_t *ui_Brightness;
void ui_event_Switch1( lv_event_t * e);
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Light_Title;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_Title);
LV_FONT_DECLARE( ui_font_Roller);
LV_FONT_DECLARE( ui_font_Brightness);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
